ISO_639_1_CODES = dict(
    afar='aa',
    akan='ak',
    amharic='am',
    arabic='ar',
    assamese='as',
    azerbaijani='az', 
    bashkir='ba',
    belarusian='be',
    bengali='bh', 
    bosnian='bs',
    breton='br',
    bulgarian='bg',
    catalan='ca',
    chechen='ce',
    cornish='kw',
    corsican='co',
    czech='cs',
    danish='da',
    divehi='dv',
    dutch='nl',
    dzongkha='dz',
    english='en',
    esperanto='eo',
    estonian='et',
    ewe='ee',
    faroese='fo',
    fijian='fj',
    finnish='fi',
    french='fr',
    fulah='ff',
    galician='gl',
    georgian='ka',
    german='de',
    greek='el',
    guarani='gn',
    gujarati='gu',
    haitian='ht',
    hausa='ha',
    hebrew='he',
    herero='hz',
    hindi='hi',
    hirimotu='ho',
    hungarian='hu',
    interlingua='ia',
    indonesian='id',
    interlingue='ie',
    irish='ga',
    igbo='ig',
    inupiaq='ik',
    ido='io',
    icelandic='is',
    italian='it',
    inuktitut='iu',
    japanese='ja',
    javanese='jv',
    kalaallisut='kl',
    kannada='kn',
    kanuri='kr',
    kasmiri='ks',
    kazakh='kk',
    khmer='km',
    kikuyu='ki',
    kinyarwanda='rw',
    kirghiz='ky',
    komi='kv',
    kongo='kg',
    korean='ko',
    kurdish='ku',
    kuanyama='kj',
    latin='la',
    luxembourgish='lb',
    ganda='lg',
    limburgan='li',
    lingala='ln',
    lao='lo',
    lithuanian='lt',
    luba_katanga='lu',
    latvian='lv',
    manx='gv',
    macedonian='mk',
    malagasy='mg',
    malay='ms',
    malayalam='ml',
    maltese='mt',
    maori='mi',
    marathi='mr',
    marshallese='mh',
    mongolian='mn',
    nauru='na',
    navajo='nv',
    north_ndebele='nd',
    nepali='ne',
    ndonga='ng',
    bokmal='nb',
    nynorsk='nn',
    norwegian='no',
    nuosu='ii',
    south_ndebele='nr',
    occitan='oc',
    ojibwa='oj',
    church_slavic='cu',
    oromo='om',
    oriya='or',
    osstian='os',
    punjabi='pa',
    pali='pi',
    persian='fa',
    polish='pl',
    pashto='ps',
    portuguese='pt',
    quechua='qu',
    romanish='rm',
    rundi='rn',
    roman='ro',
    russian='ru',
    sanskrit='sa',
    sardinian='sc',
    sindhi='sd',
    sarni='se',
    samoan='sm',
    sango='sg',
    serbian='sr',
    gaelic='gd',
    shona='sn',
    sinhala='si',
    slovak='sk',
    slovenian='sl',
    somali='so',
    sotho='st',
    spanish='es',
    sudanese='su',
    swahili='sw',
    swati='ss',
    swedish='sv',
    tamil='ta',
    telugu='te',
    tajik='tg',
    thai='th',
    tigrinya='ti',
    tibetan='bo',
    turkmen='tk',
    tagalog='tl',
    tswana='tn',
    tonga='to',
    turkish='tr',
    tsonga='ts',
    tatar='tt',
    twi='tw',
    tahitian='ty',
    uighur='ug',
    ukranian='uk',
    urdu='ur',
    uzbek='uz',
    venda='ve',
    vietnamese='vi',
    volapuk='vo',
    walloon='wa',
    welsh='cy',
    wolof='wo',
    frisian='fy',
    yiddish='yi',
    yoruba='yo',
    zhuang='za',
    zulu='zu'
)

# Maps api to required query params
MODES_AND_PARAMS = {
    'ip_geolocation': {
        'ip-geolocation': ('ip', 'localityLanguage', 'key'),
        'ip-geolocation-full': ('ip', 'localityLanguage', 'key'),
        'ip-geolocation-with-confidence': ('ip', 'localityLanguage', 'key'),
        },
    'geocoding': {
        'reverse-geocode-client': ('latitude', 'longitude', 'localityLanguage'),
        'reverse-geocode': ('latitude', 'longitude','localityLanguage', 'key'),
    },
    'client_info': {
        'client-info': (),
        'am-i-roaming': ('latitude', 'longitude'),
        'user-agent-info': ('userAgentRaw', 'key'),
        'client-ip': ()
    },
    'timezone': {
        'timezone-by-ip': ('ip', 'utcReference', 'key'),
        'timezone-info': ('timeZoneId', 'utcReference', 'key'),
        'timezone-by-location': ('latitude', 'longitude', 'utcReference', 'key'),
    },
    'country_info': {
        'country-by-ip': ('ip', 'localityLanguage', 'key'),
        'country-info': ('code', 'localityLanguage', 'key')
    },
    'asn_info': {
        'asn-info': ('asn', 'localityLanguage', 'key'),
        'asn-info-full': ('asn', 'localityLanguage', 'key'),
    },
    'insights': {
        'tor-exit-nodes-list': ('batchSize', 'offset', 'localityLanguage', 'key'),
        'address-space-stats-ipv4': ('key', '')
    },
    'network': {
        'network-by-ip': ('ip', 'localityLanguage', 'key'),
        'prefixes-list': ('bogonsOnly', 'batchSize', 'offset', 'localityLanguage', 'key'),
        'network-by-cidr': ('cidr', 'depthLimit', 'bogonsOnly', 'asn', 'localityLanguage', 'key')
    },
    'phone_number': {
        'phone-number-validate-by-ip': ('number', 'ip', 'localityLanguage', 'key'),
        'phone-number-validate': ('number', 'countryCode', 'localityLanguage', 'key'),
    },
    'email_validation': {
        'email-verify': ('emailAddress', 'key')
    }
}
 